name: CI/CD Pipeline


on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend jar
        working-directory: backend
        run: cmd /c mvnw.cmd clean package -DskipTests

      - name: Build backend Docker image
        run: docker build -t devops-assignment-backend:latest ./backend

      - name: Build frontend Docker image
        run: docker build -t devops-assignment-frontend:latest ./frontend

      - name: Load backend image into Minikube
        run: wsl minikube image load devops-assignment-backend:latest

      - name: Load frontend image into Minikube
        run: wsl minikube image load devops-assignment-frontend:latest

      - name: Apply Kubernetes files
        run: wsl bash -lc "cd /mnt/c/actions-runner/_work/Devops-Viatab/Devops-Viatab && kubectl apply -f k8s/"

      - name: Restart backend deployment
        run: wsl kubectl rollout restart deployment viatab-backend

      - name: Restart frontend deployment
        run: wsl kubectl rollout restart deployment viatab-frontend 